[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r services/gateway/requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd services/gateway && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"